from ._format_ax import *
from .figure_0 import *
from .figure_1 import *
from .figure_2 import *
from .figure_3 import *
from .figure_4 import *
from .figure_5 import *
from .figure_6 import *
from .figure_7 import *
from .figure_8 import *
from .figure_9 import *
